### ISSUE TITLE
Deckard throws typeerrors on desktop browsers

### ISSUE THREAD

**Issue by kpeatt** [mobify/deckard#9] opened 2015-03-16 22:32 UTC
When I resize desktop chrome I get this error:

```js
Uncaught TypeError: Cannot read property 'orientation' of undefined
```

You can reproduce this in Pinny master by dragging the window size around.

**Comment by tedtate** [comment] 2015-03-18 21:55
Closing, error caused by an old version of deckard (0.0.1) being used.

**Closed by tedtate** 2015-03-18 21:55 UTC
Labels: bug
